development: &default
  adapter: postgresql
  database: epa_rfi_development
  encoding: utf8
#  host: 172.17.0.2
  min_messages: warning
  pool: 2
  timeout: 5000

local:
  <<: *default
  adapter: postgresql
  database: epa_rfi_development
  host: localhost

development:
  <<: *default
  adapter:  postgresql
  database: epa_rfi_development

test:
  <<: *default
  database: epa_rfi_test

production:
  <<: *default
  database: epa_rfi_production

docker: &docker
  adapter: postgresql
  database: epa_rfi_development
  encoding: utf8
  username: postgres
  password:
  host: db
  pool: 5

docker-test:
  <<: *docker
  database: epa_rfi_test

docker-prod:
  <<: *docker
  database: epa_rfi_production
